### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by erycken** [TheVieiraAkA/MMM-MyTraktSeries#1]
Mirror will boot fine however module is stuck 'Loading'.
`
0|MagicMir |MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|MagicMir | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|MagicMir | Whoops! There was an uncaught exception...
0|MagicMir | TypeError: Error processing argument at index 1, conversion failure from 80
0|MagicMir |     at TypeError (native)
0|MagicMir |     at ClientRequest.setHeader (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:252:21)
0|MagicMir |     at ClientRequest (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:190:14)
0|MagicMir |     at Net.request (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/browser/api/net.js:354:10)
0|MagicMir |     at get (/home/pi/MagicMirror/modules/MMM-MyTraktSeries/node_modules/got/index.js:49:18)
0|MagicMir |     at Immediate.setImmediate (/home/pi/MagicMirror/modules/MMM-MyTraktSeries/node_modules/got/index.js:124:3)
0|MagicMir |     at runCallback (timers.js:574:20)
0|MagicMir |     at tryOnImmediate (timers.js:554:5)
0|MagicMir |     at processImmediate [as _immediateCallback] (timers.js:533:5)
`
I have the module configured as directed.

**Comment by caiminnl** [comment]
Same problem here..
